### ISSUE TITLE
Update map message

### ISSUE THREAD

**Issue by TriForceX** [FlendoJK2/JK2SPMaps#1]
I think the map names should be separated from the description "Remodded By Flendo" also remove the capitalized text, and change the "Remodded" word to "Remade" or "Modded" because in the main document you describe them as "Remaded maps" not "Remodded maps", It cant be "Remodded" because the maps wasnt "modded" previously.

For example:
```
Artus Topside Remodded By Flendo
```
To:
```
Artus Topside - Remade by Flendo
```

**Comment by FlendoJK2** [comment]
Yes, you are right, every message on the map is now changed. Thanks for the proposal!
